// saas-dark v1.0.0 — design-engine
// Typed export. Values resolve via CSS custom properties at runtime.

export const tokens = {
  name: "saas-dark",
  version: "1.0.0",
  modes: ["light", "dark"] as const,
  defaultMode: "dark" as const,

  color: {
    primitive: {
      grey: {
        0:   "oklch(1.000 0.000 0)",
        50:  "oklch(0.980 0.003 264)",
        100: "oklch(0.950 0.005 264)",
        200: "oklch(0.900 0.008 264)",
        300: "oklch(0.800 0.012 264)",
        400: "oklch(0.650 0.018 264)",
        500: "oklch(0.500 0.020 264)",
        600: "oklch(0.380 0.018 264)",
        700: "oklch(0.280 0.015 264)",
        800: "oklch(0.200 0.012 264)",
        900: "oklch(0.140 0.008 264)",
        950: "oklch(0.100 0.005 264)",
      },
      accent: {
        50:  "oklch(0.970 0.040 149)",
        100: "oklch(0.930 0.080 149)",
        200: "oklch(0.880 0.130 149)",
        300: "oklch(0.820 0.170 149)",
        400: "oklch(0.770 0.200 149)",
        500: "oklch(0.720 0.219 149)",
        600: "oklch(0.660 0.219 149)",
        700: "oklch(0.580 0.200 149)",
        800: "oklch(0.480 0.170 149)",
        900: "oklch(0.380 0.130 149)",
        950: "oklch(0.280 0.090 149)",
      },
      success: "oklch(0.720 0.170 145)",
      warning: "oklch(0.780 0.180 65)",
      error:   "oklch(0.620 0.220 20)",
      info:    "oklch(0.680 0.180 240)",
      chart: {
        1: "oklch(0.620 0.180 220)",
        2: "oklch(0.700 0.170 65)",
        3: "oklch(0.620 0.150 145)",
        4: "oklch(0.700 0.150 95)",
        5: "oklch(0.580 0.180 290)",
        6: "oklch(0.700 0.180 30)",
        7: "oklch(0.640 0.140 200)",
        8: "oklch(0.500 0.020 264)",
      },
    },
    semantic: {
      bgBase:        "var(--bg-base)",
      bgSurface:     "var(--bg-surface)",
      bgElevated:    "var(--bg-elevated)",
      bgOverlay:     "var(--bg-overlay)",
      bgInset:       "var(--bg-inset)",
      textPrimary:   "var(--text-primary)",
      textSecondary: "var(--text-secondary)",
      textTertiary:  "var(--text-tertiary)",
      textDisabled:  "var(--text-disabled)",
      textInverse:   "var(--text-inverse)",
      textLink:      "var(--text-link)",
      borderSubtle:  "var(--border-subtle)",
      borderDefault: "var(--border-default)",
      borderStrong:  "var(--border-strong)",
      borderFocus:   "var(--border-focus)",
      accent:        "var(--accent)",
      accentHover:   "var(--accent-hover)",
      accentPress:   "var(--accent-press)",
      accentSubtle:  "var(--accent-subtle)",
      accentText:    "var(--accent-text)",
      success:       "var(--success)",
      successSubtle: "var(--success-subtle)",
      successText:   "var(--success-text)",
      warning:       "var(--warning)",
      warningSubtle: "var(--warning-subtle)",
      warningText:   "var(--warning-text)",
      error:         "var(--error)",
      errorSubtle:   "var(--error-subtle)",
      errorText:     "var(--error-text)",
      info:          "var(--info)",
      infoSubtle:    "var(--info-subtle)",
      infoText:      "var(--info-text)",
    },
    component: {
      buttonBgPrimary:        "var(--button-bg-primary)",
      buttonBgPrimaryHover:   "var(--button-bg-primary-hover)",
      buttonBgPrimaryPress:   "var(--button-bg-primary-press)",
      buttonTextPrimary:      "var(--button-text-primary)",
      buttonBgSecondary:      "var(--button-bg-secondary)",
      buttonTextSecondary:    "var(--button-text-secondary)",
      buttonBorderSecondary:  "var(--button-border-secondary)",
      buttonBgGhost:          "var(--button-bg-ghost)",
      buttonBgGhostHover:     "var(--button-bg-ghost-hover)",
      buttonTextGhost:        "var(--button-text-ghost)",
      buttonBgDestructive:    "var(--button-bg-destructive)",
      buttonTextDestructive:  "var(--button-text-destructive)",
      inputBg:                "var(--input-bg)",
      inputText:              "var(--input-text)",
      inputPlaceholder:       "var(--input-placeholder)",
      inputBorder:            "var(--input-border)",
      inputBorderFocus:       "var(--input-border-focus)",
      inputBorderError:       "var(--input-border-error)",
      cardBg:                 "var(--card-bg)",
      cardBorder:             "var(--card-border)",
      cardBgHover:            "var(--card-bg-hover)",
      navBg:                  "var(--nav-bg)",
      navText:                "var(--nav-text)",
      navTextActive:          "var(--nav-text-active)",
      navBgActive:            "var(--nav-bg-active)",
      tableRowBg:             "var(--table-row-bg)",
      tableRowBgHover:        "var(--table-row-bg-hover)",
      tableHeaderBg:          "var(--table-header-bg)",
      tableCellBorder:        "var(--table-cell-border)",
      badgeBg:                "var(--badge-bg)",
      badgeText:              "var(--badge-text)",
      modalBg:                "var(--modal-bg)",
      modalOverlay:           "var(--modal-overlay)",
      modalBorder:            "var(--modal-border)",
      toastBg:                "var(--toast-bg)",
    },
  },

  typography: {
    font: {
      display: "var(--font-display)",
      body:    "var(--font-body)",
      mono:    "var(--font-mono)",
    },
    size: {
      xs:       { size: "12px", lineHeight: "1.6", letterSpacing: "0.01em",  weight: 400 },
      smDense:  { size: "13px", lineHeight: "1.5", letterSpacing: "0",       weight: 400 },
      sm:       { size: "14px", lineHeight: "1.5", letterSpacing: "0",       weight: 400 },
      base:     { size: "16px", lineHeight: "1.6", letterSpacing: "-0.01em", weight: 400 },
      lg:       { size: "20px", lineHeight: "1.4", letterSpacing: "-0.02em", weight: 500 },
      xl:       { size: "24px", lineHeight: "1.3", letterSpacing: "-0.02em", weight: 600 },
      "2xl":    { size: "32px", lineHeight: "1.2", letterSpacing: "-0.03em", weight: 600 },
      "3xl":    { size: "40px", lineHeight: "1.1", letterSpacing: "-0.04em", weight: 700 },
      "4xl":    { size: "56px", lineHeight: "1.0", letterSpacing: "-0.05em", weight: 700 },
    },
  },

  spacing: {
    0:  "0",
    1:  "4px",
    2:  "8px",
    3:  "12px",
    4:  "16px",
    6:  "24px",
    8:  "32px",
    12: "48px",
    16: "64px",
    24: "96px",
    32: "128px",
  },

  radius: {
    none: "0",
    sm:   "4px",
    md:   "6px",
    lg:   "8px",
    xl:   "12px",
    "2xl": "16px",
    full: "9999px",
  },

  border: {
    thin:   "1px",
    medium: "1.5px",
    thick:  "2px",
  },

  shadow: {
    xs:    "var(--shadow-xs)",
    sm:    "var(--shadow-sm)",
    md:    "var(--shadow-md)",
    lg:    "var(--shadow-lg)",
    xl:    "var(--shadow-xl)",
    focus: "var(--shadow-focus)",
  },

  motion: {
    duration: {
      instant:    "0ms",
      fast:       "100ms",
      normal:     "150ms",
      slow:       "250ms",
      deliberate: "400ms",
      spring:     "350ms",
    },
    easing: {
      out:    "cubic-bezier(0, 0, 0.2, 1)",
      in:     "cubic-bezier(0.4, 0, 1, 1)",
      inOut:  "cubic-bezier(0.4, 0, 0.2, 1)",
      spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
    },
  },
} as const;

export type Tokens = typeof tokens;
export default tokens;
